set_property PACKAGE_PIN L17 [get_ports MCLK]
set_property PACKAGE_PIN M3 [get_ports SCL]
set_property PACKAGE_PIN J3 [get_ports SDA]
set_property IOSTANDARD LVCMOS33 [get_ports MCLK]
#set_property IOSTANDARD LVCMOS33 [get_ports nRST]
set_property IOSTANDARD LVCMOS33 [get_ports SCL]
set_property IOSTANDARD LVCMOS33 [get_ports SDA]


set_property PACKAGE_PIN W3 [get_ports O_ADDRESS_READY]
set_property IOSTANDARD LVCMOS33 [get_ports O_ADDRESS_READY]
set_property IOSTANDARD LVCMOS33 [get_ports O_RD]
set_property IOSTANDARD LVCMOS33 [get_ports O_WR]
set_property PACKAGE_PIN V2 [get_ports O_RD]
set_property PACKAGE_PIN W2 [get_ports O_WR]
set_property PACKAGE_PIN U1 [get_ports {COUNT[1]}]
set_property PACKAGE_PIN T2 [get_ports {COUNT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COUNT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {COUNT[0]}]
