set_property IOSTANDARD LVCMOS33 [get_ports {PWM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ready]
set_property IOSTANDARD LVCMOS33 [get_ports inter_ready]
set_property PACKAGE_PIN G17 [get_ports {PWM[3]}]
set_property PACKAGE_PIN V13 [get_ports {PWM[2]}]
set_property PACKAGE_PIN V14 [get_ports {PWM[1]}]
set_property PACKAGE_PIN U14 [get_ports {PWM[0]}]
set_property PACKAGE_PIN L17 [get_ports CLK]
set_property PACKAGE_PIN G19 [get_ports inter_ready]
set_property PACKAGE_PIN N18 [get_ports ready]

