set_property PACKAGE_PIN L17 [get_ports CLK]
set_property PACKAGE_PIN G19 [get_ports finish]
set_property PACKAGE_PIN J19 [get_ports ready]
set_property PACKAGE_PIN G17 [get_ports {PWM[3]}]
set_property PACKAGE_PIN K18 [get_ports reset]
set_property PACKAGE_PIN R18 [get_ports {PWM[2]}]
set_property PACKAGE_PIN P18 [get_ports {PWM[1]}]
set_property PACKAGE_PIN U16 [get_ports {PWM[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports finish]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports ready]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PWM[0]}]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets CLK_IBUF]
#create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports { CLK100MHZ }];

