set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports scl]
set_property IOSTANDARD LVCMOS33 [get_ports sda]
set_property PACKAGE_PIN L17 [get_ports clk]
set_property PACKAGE_PIN M3 [get_ports scl]
set_property PACKAGE_PIN J3 [get_ports sda]
set_property PACKAGE_PIN L3 [get_ports en]

set_property PACKAGE_PIN L3 [get_ports enable]
set_property IOSTANDARD LVCMOS33 [get_ports enable]

set_property IOSTANDARD LVCMOS33 [get_ports LED_1]
set_property IOSTANDARD LVCMOS33 [get_ports LED_2]
set_property PACKAGE_PIN A17 [get_ports LED_1]
set_property PACKAGE_PIN C16 [get_ports LED_2]
