set_property PACKAGE_PIN L17 [get_ports mclk]
set_property IOSTANDARD LVCMOS33 [get_ports mclk]

#set_property PACKAGE_PIN L17 [get_ports MCLK]
#set_property IOSTANDARD LVCMOS33 [get_ports MCLK]

#set_property IOSTANDARD LVCMOS33 [get_ports InPWM]
#set_property IOSTANDARD LVCMOS33 [get_ports Debug]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[11]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[10]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[9]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[8]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[7]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {OutPWM[0]}]
#set_property PACKAGE_PIN V8 [get_ports InPWM]
#set_property PACKAGE_PIN U8 [get_ports {OutPWM[0]}]
#set_property PACKAGE_PIN W7 [get_ports {OutPWM[1]}]
#set_property PACKAGE_PIN U7 [get_ports {OutPWM[2]}]
#set_property PACKAGE_PIN U3 [get_ports {OutPWM[3]}]
#set_property PACKAGE_PIN W6 [get_ports {OutPWM[4]}]
#set_property PACKAGE_PIN U2 [get_ports {OutPWM[5]}]
#set_property PACKAGE_PIN U5 [get_ports {OutPWM[6]}]
#set_property PACKAGE_PIN W4 [get_ports {OutPWM[7]}]
#set_property PACKAGE_PIN V5 [get_ports {OutPWM[8]}]
#set_property PACKAGE_PIN U4 [get_ports {OutPWM[9]}]
#set_property PACKAGE_PIN V4 [get_ports {OutPWM[10]}]
#set_property PACKAGE_PIN W5 [get_ports {OutPWM[11]}]
#set_property PACKAGE_PIN V3 [get_ports Debug]

